### ISSUE TITLE
remote throws exception in aapp_list

### ISSUE THREAD

**Issue by gbrissey** [xchwarze/samsung-tv-ws-api#1]
following the example every call works until the app_list call
'''
remote.py
line: 177  if response.get('data') and response.get('data').get('data'):
 result in exception because the returned response dosen't have a data embedded in data
    'response.get('data').get('data')'  the json returned by my Samsung Q8FN  doesn't have much in it.

response = 
    {'data': 200, 'event': 'ed.apps.launch', 'from': 'host'}
     'data':200
     'event':'ed.apps.launch'
     'from':'host'
    __len__:3
  
'''

**Comment by xchwarze** [comment]
hello @gbrissey
please edit remote.py like this:
`
response = json.loads(self.connection.recv())
logging.info('Response: %s', response)
`
And show me the result

**Comment by gbrissey** [comment]
the results
INFO:root:Opening url in browser https://duckduckgo.com/
INFO:root:Sending run app app_id: org.tizen.browser app_type: NATIVE_LAUNCH meta_tag: https://duckduckgo.com/
DEBUG:root:WS url wss://192.168.1.xx:8002/api/v2/channels/samsung.remote.control?name=U2Ftc3VuZ1R2UmVtb3Rl&token=######
INFO:root:Get app list
INFO:root:Response: {'from': 'host', 'data': 200, 'event': 'ed.apps.launch'}

then the exception as describe above

**Comment by gilvitzi** [comment]
I got the same exception. 
After debugging it, it appears the socket has many other messages and the next message to read is not necessarily the response for the app list we just requested.

I think the best way to handle this is to have another code flow (possibly another thread) only reading the messages from the websocket and the notifying others if a message they requested has arrived.

I have some code written already, and could finish it and make a pull request.

**Comment by xchwarze** [comment]
For some time I am thinking of making a refactor of that.
Maybe using run_forever() fix that

**Comment by gilvitzi** [comment]
Do you mean using python's asyncio event loop ? 
if so, I believe this will require a big refactor, possibly converting the whole library to be async, including changing the websocket library to [websockets](https://websockets.readthedocs.io/en/stable/intro.html) which is an async websocket library.

This will be great to see, but it's a big change, so I suggest in the meantime to add a threaded solution.

I will create a pull request for you to review.

**Comment by xchwarze** [comment]
'event': 'ed.apps.launch' is nos supported in all tizen versions
