### ISSUE TITLE
Ability to pass in an SSLContext

### ISSUE THREAD

**Issue by bdraco** [xchwarze/samsung-tv-ws-api#119]
https://github.com/xchwarze/samsung-tv-ws-api/blob/ae5d2b33cf8bca63fb7c7025724d136ece40be95/samsungtvws/async_connection.py#L70

It would be great if we could pass in an SSLContext so on retry one isn't recreated every time

<img width="1218" alt="Screenshot 2023-04-30 at 9 07 53 AM" src="https://user-images.githubusercontent.com/663432/235359917-f3d9359b-114b-4998-9342-0672c24243e7.png">

**Comment by bdraco** [comment]
Another option which is probably a lot easier is to make the ssl context a singleton

**Comment by epenet** [comment]
I opened https://github.com/xchwarze/samsung-tv-ws-api/pull/121
