### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ivmarkov** [xchwarze/samsung-tv-ws-api#126]
The codebase of this project lists at least three different licenses:
* MIT [here](https://github.com/xchwarze/samsung-tv-ws-api/blob/master/LICENSE)
* GPL2 [here, at the bottom](https://github.com/xchwarze/samsung-tv-ws-api#readme)
* LGPL2 [here, and in other `.py` files](https://github.com/xchwarze/samsung-tv-ws-api/blob/master/samsungtvws/rest.py)

Which one is it?

**Comment by xchwarze** [comment]
I never finished implementing it but the idea was to put GPLv2 on the whole project.

**Comment by ivmarkov** [comment]
Thanks for reacting so quickly! I can't really use code licensed under GPLV2. For libraries, this is (IMO) very, very problematic.

**Comment by xchwarze** [comment]
@ivmarkov I don't know if it will help you but I am changing the license of all my current projects to LGPL-3.0.
