### ISSUE TITLE
[FR] Detect device type

### ISSUE THREAD

**Issue by chemelli74** [xchwarze/samsung-tv-ws-api#14]
I was pointed to your library from a HA developer.

We would like to detect the device type as some cannot be controlled in HA, like Soundbar.
See [0.109.b4: Samsung sound bar detected as TV](https://github.com/home-assistant/core/issues/34810) for reference.

Both my TV and my Soundbar replies to http://<ip_address>:9197/dmr

So I think it would be possible to add the vdProductType:

```
<root>
  <device>
     <sec:ProductCap>
               ... , ... , vdProductType=SOUNDBAR , ...

```

Thank you,

Simone

**Comment by xchwarze** [comment]
https://github.com/xchwarze/samsung-tv-ws-api/issues/7#issuecomment-587207996

**Comment by chemelli74** [comment]
> [#7 (comment)](https://github.com/xchwarze/samsung-tv-ws-api/issues/7#issuecomment-587207996)
> 
> > Originally my roadmap was to make a second library to handle DLNA and through that I can use everything that is multimedia.
> > But unfortunately I did not get to do it

Thx for the update.

Do you mind considering adding the request to current implementation ?
Endpoint "**/dmr**" is already used, so adding 1 more info should be feasible.

Am I wrong ?

Simone

**Comment by xchwarze** [comment]
* this library is a wrapper from samsung.remote.control v2 (which comes installed on all tyzen televisions)

* a second library would have to be made to handle DLNA

* I understand that the linked bug is solved by implementing rest_device_info()
