### ISSUE TITLE
Requirement is pinned for samsungtvws 1.4.0: websocket-client==0.56.0

### ISSUE THREAD

**Issue by MartinHjelmare** [xchwarze/samsung-tv-ws-api#16]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by xchwarze** [comment]
Hi! As far as I remember, this is done like this because of a bug in the current version. 
I'm waiting for this to be solved to make the change

**Comment by xchwarze** [comment]
https://github.com/websocket-client/websocket-client/issues/595
https://github.com/xchwarze/samsung-tv-ws-api/issues/4

**Comment by MartinHjelmare** [comment]
It may be possible to workaround this bug by setting a custom header with the correct capitalization.

**Comment by xchwarze** [comment]
@MartinHjelmare fixed in last version!
https://pypi.org/project/samsungtvws/1.6.0/

**Comment by MartinHjelmare** [comment]
Thanks! 👍
