### ISSUE TITLE
Feature Request - Get Channel List

### ISSUE THREAD

**Issue by kaoh** [xchwarze/samsung-tv-ws-api#18]
It would be nice to know in advance which channel maps to which TV station to make an external remote control useful. Is there any way getting the current sender list using the implemented web / REST API? Is there an alternative? I do not want to use an additional database which must be manually synced with the Samsung TV to have this convenience feature.

**Comment by kaoh** [comment]
This is now implemented, because it was closed?

**Comment by xchwarze** [comment]
Because of all the applications that use WS that I reviewed to make them RE, I did not find any that have it.
I suppose that it is done outside the service that I use in this dependency or that it cannot be done

**Comment by kaoh** [comment]
Ok, thanks for the reply. Sad that Samsung did not add an API to retrieve the channel list.
