### ISSUE TITLE
Get Ambient Mode Status

### ISSUE THREAD

**Issue by Buhtigs** [xchwarze/samsung-tv-ws-api#19]
I am searching a way to check if the TV is currently in Ambient Mode or not. But i don't know where in the API this information is available.. i would like to complement the class SamsungTVWS with such a function.

**Comment by xchwarze** [comment]
@Buhtigs maybe the info command show this info.
Use rest_device_info() method and check the result

**Comment by Buhtigs** [comment]
Thank you for the hint. I already checked that, this only returns a field 'PowerState' which can be 'on' or 'standby'. I shows 'on' when Ambient Mode is on. But it shows also 'on' when the TV is on for watching a movie.
