### ISSUE TITLE
a bug in library?

### ISSUE THREAD

**Issue by Reikagilu** [xchwarze/samsung-tv-ws-api#22]
i'm want to make an integrated control with alexa for my samsung TV, because so far my alexa only allows turning the tv on or off, not being able to increase or decrease the volume, or even change the app
and i think i found a problem in the library
when you run the command tv.run_app(code_for_app) the first time it works normally, but you kind of have time to change the app again and that time is less than 30 seconds, if you try to change the app after that it won't work and the next time you try the program it just breaks with the error "Broken Pipe"

**Comment by xchwarze** [comment]
Each version of Tizen works slightly differently.
The intention of the library is that it works in all of them, so if in your use case you need a sleep () you can add it in your implementation.

**Comment by Reikagilu** [comment]
i  dont know if it's the best way, but i solve this problem creating a connection for each time i change the app
i need to close the conection too? if yes, how i close?

**Comment by xchwarze** [comment]
what version of tyzen do you have?

**Comment by Reikagilu** [comment]
sorry, how can i check this?

**Comment by xchwarze** [comment]
execute rest_device_info() and paste here the device info

```python
# Get device info (device name, model, supported features..)
info = tv.rest_device_info()
logging.info(info)
```

**Comment by Reikagilu** [comment]
2.0.25
