### ISSUE TITLE
app_list() doesn't return

### ISSUE THREAD

**Issue by m439** [xchwarze/samsung-tv-ws-api#23]
Hi, 

I'm using a Samsung GU65TU7079UXZG (it's in the 2020 Basic1 category with Tizen 5.5) and I sending keys via shortcuts works just fine. But when I call app_list(), the function doesn't return (probably waiting for receiving data from the tv).

**Comment by xchwarze** [comment]
Tizen 5 dont suport this command anymore.
I am seeing if in any forum someone has the new command.
As Samsung is an idiot company, it does not provide documentation about it and everything has to be done with reverse engineering.
