### ISSUE TITLE
TCP/IP API docs?

### ISSUE THREAD

**Issue by d3caf** [xchwarze/samsung-tv-ws-api#29]
Hey there,

I'm wanting to work on my own WS API for my Frame TV and I was just wondering if you were able to find docs for how the WS API works. I've scoured Samsung's site and wasn't able to find any mention of it. I assume it has something to do with the SmartView SDK?

Sorry if this is the wrong place for such a question; I wasn't sure how else to get in touch.

Thanks for the library!

**Comment by xchwarze** [comment]
There is no public documentation about it.
This library is developed mainly thanks to reverse engineering.

**Comment by d3caf** [comment]
Thanks for the response :)
