### ISSUE TITLE
app_list() loads forever

### ISSUE THREAD

**Issue by kilian579** [xchwarze/samsung-tv-ws-api#30]
I've just tried out your repository on a "The Frame 2021".
It is possible to establish a connection and to use the shortcuts.

However when I try to load the list of apps via `apps = tv.app_list()` nothing happens, it just loads forever.
I'm guessing the `recv` function you are using is blocking the thread, and not receiving anything.

Did you face this issue before and have any tips on how to handle it?
Could you implement a timeout (eg. 3 seconds) in the `recv` function?

Thanks for your work!

**Comment by epenet** [comment]
Could you try the new async version to see if it helps?

```python
import aiohttp
import asyncio
import logging

from samsungtvws.async_remote import SamsungTVWSAsyncRemote
from samsungtvws.async_rest import SamsungTVAsyncRest

logging.basicConfig(level=logging.DEBUG)

host = "xxx.xxx.xxx.xxx"
port = 8002


async def main():
    async with aiohttp.ClientSession() as session:
        rest_api = SamsungTVAsyncRest(host=host, port=port, session=session)
        logging.info(await rest_api.rest_device_info())

    tv = SamsungTVWSAsyncRemote(host=host, port=port, token_file="token_file")
    await tv.start_listening()
    logging.info(await tv.app_list())
    await tv.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```
