### ISSUE TITLE
Async version

### ISSUE THREAD

**Issue by epenet** [xchwarze/samsung-tv-ws-api#31]
Hi @xchwarze

Do you have plans for an async version of the API?
If not, would you accept PRs to implement this?

**Comment by xchwarze** [comment]
hello!
Since I have several projects, unfortunately, I was never able to finish implementing it. 

There was already a pull request about it, but due to time constraints I couldn't work on it
https://github.com/xchwarze/samsung-tv-ws-api/pull/11 

If you want you can use it as a base or do it your way

**Comment by epenet** [comment]
I saw #11, but that's not really making it async... It will cause a thread to be created and locked for the duration of the instance.
My idea was a create a proper `async` version using `websockets` library for the websocket code, and `aiohttp` (or `httpx`) for the rest API.

It will result in a chunk of duplicate code but I think it is still better than creating a separate library.

**Comment by xchwarze** [comment]
seem right
send the pr with the version increased to 2.0

**Comment by xchwarze** [comment]
hello!
I'm traveling and I don't have a TV to test dependency on.
Did you fully test it?
Could you also remove the warning of using https without a valid certificate?

**Comment by xchwarze** [comment]
Now that I remember, the documentation is completely up to date to make a release?

**Comment by epenet** [comment]
Regarding the documentation, I haven't touched it.
All the `sync` stuff should continue working as it currently does. The `async` stuff will need to be documented - but maybe that can be done after the release?
Or maybe you can build a pre-release?

cc @bdraco

**Comment by epenet** [comment]
> Did you fully test it?
I only have one TV to test it with, and it works great with async.

> Could you also remove the warning of using https without a valid certificate?
I don't get any warnings on the async version, and I wasn't planning to make amends.

**Comment by epenet** [comment]
I have run some extra checks with the sync version (ie. HA dev branch + latest library) and the only issue is the endpoint argument for the `open()` method.
I think since it was a breaking change in 1.7.0 (argument wasn't there in 1.6.0) it's ok to make a breaking change here also.

**Comment by xchwarze** [comment]
Well, as soon as I can, I'll release the 2.0 version.
If you could update the documentation that would be great.

**Comment by xchwarze** [comment]
@epenet the release is uploaded

**Comment by epenet** [comment]
Thanks.
I updated the dependency inside HA: https://github.com/home-assistant/core/pull/67351

I had to use the commit id for the reference though because you didn't tag it 😉

**Comment by epenet** [comment]
It would be great if you could publish a new release after #62 is accepted and merged

**Comment by xchwarze** [comment]
done!
