### ISSUE TITLE
.open() hangs

### ISSUE THREAD

**Issue by HTenkanen** [xchwarze/samsung-tv-ws-api#4]
Hi guys,

thanks for writing this nice library! 

I found something that breaks things on my own setup.

When opening the connection to my TV, the following lines of code in `remote.py` stalls the connection. After commenting out the lines, everything starts working normally. Just wondering that should these lines be isolated from the `open()` method?: 
https://github.com/xchwarze/samsung-tv-ws-api/blob/master/samsungtvws/remote.py#L112-L121

**Comment by gilvitzi** [comment]
I didn't write the code, but my thoughts are that maybe your TV does not support Auth Tokens.
If this is the case, it could be that the code that waits for the token message right after connecting will hang.

You could try running the following code, it should work at least on some models and return info about the device supported features:

```python
IP = '192.168.0.X'
import requests
res = requests.get('http://{}:8001/api/v2/'.format(IP))
device_info = json.loads(res.text)
isSupport = device_info.get('isSupport')
print(isSupport)
```

isSupport should have `"TokenAuthSupport": "true"` if the TV support it, otherwise it could be false or omitted.

**Comment by HTenkanen** [comment]
@gilvitzi Thanks for your quick reply! 

Tested this, but it seems that Auth Tokens are supported. This is what the code snippet returned:

```
{"DMP_DRM_PLAYREADY":"false","DMP_DRM_WIDEVINE":"false","DMP_available":"true","EDEN_available":"true","FrameTVSupport":"false","ImeSyncedSupport":"true","TokenAuthSupport":"true","remote_available":"true","remote_fourDirections":"true","remote_touchPad":"true","remote_voiceControl":"false"}
```

**Comment by HTenkanen** [comment]
This seems to be related to websocket `.recv()` -function and that not returning data. I've been able to retrieve e.g. token information with nodejs `wscat` package:
`wscat -n --connect wss://192.168.0.XX:8002/api/v2/channels/samsung.remote.control`

But unfortunately have not succeeded to repeat this with any Python libraries so far.

**Comment by HTenkanen** [comment]
Might relate to this:
https://github.com/websocket-client/websocket-client/issues/437

**Comment by HTenkanen** [comment]
Possibly related:
https://github.com/websocket-client/websocket-client/issues/595

**Comment by xchwarze** [comment]
hi! test with this version
https://pypi.org/project/samsungtvws/1.2.0/

**Comment by HTenkanen** [comment]
@xchwarze Thanks, now it works 👍
