### ISSUE TITLE
Support for J and H models

### ISSUE THREAD

**Issue by epenet** [xchwarze/samsung-tv-ws-api#67]
Hi @xchwarze

I could not find a library for communicating with the J and H models on pypi.

How would you feel about adding support for these inside this package, using as a base the work from https://github.com/eclair4151/SmartCrypto and https://github.com/kdschlosser/samsungctl?

**Comment by xchwarze** [comment]
The intention of this wrapper is to support what is standardized in the Tizen ecosystem (like samsung.remote.control or com.samsung.art-app)
I think it would make more sense to add support for DLNA/UPnP. Although the original idea I had was to make a second library for that...

When they implemented this library in HA I mentioned that the most logical thing was to make two components (SamsungTizen and SamsungLegacy) because all the things that can be done under Tizen cannot be done under legacy and that gave a confusing user experience

**Comment by epenet** [comment]
In between SamsungTizen (using this library) and SamsungLegacy (using the old samsungctl library) we need to have a way to communicate with the SamsungEncrypted models.
If you really don't want to implement it in this library, then I will create a separate library :( I won't force you into anything...

**Comment by xchwarze** [comment]
And if make a second dependency? Something like samsung-tv-legacy-api for put the pre-tizen tvs

**Comment by epenet** [comment]
Would you make `samsung-tv-encrypted-api` and `samsung-tv-legacy-api`?
For me the priority would be `samsung-tv-encrypted-api` for J and H

**Comment by xchwarze** [comment]
Ok!
I'm still traveling for a few more days so I'll probably do this when I'm in town

**Comment by epenet** [comment]
This is a potential starting point for the encrypted library:
https://github.com/epenet/home-assistant-core/tree/samsungtv-encrypted/homeassistant/components/samsungtv/encrypted

- `encrypted/__init__.py` (root)
- `encrypted/authenticator.py` (a class to follow the authentication steps - display PIN, input PIN, get token, get session - needed for config flow)
- `encrypted/command.py` (similar to ws API)
- `encrypted/remote.py` (similar to ws API)
- `encrypted/session.py` (used by remote to encrypt commands - could be moved inside remote)
- `test_authenticator.py` (a manual script to test the authentication steps - could be just in documentation)

**Comment by xchwarze** [comment]
I'll try to start it this weekend!

**Comment by epenet** [comment]
I have adjusted the latest code to use `cryptography` instead of `pycryptodome`

These are the updated dependencies:
- `aiohttp>=3.8.1`
- `py3rijndael>=0.3.3`
- `cryptography>=35.0.0`
- `websockets>=10.2`

**Comment by epenet** [comment]
I have also managed to drop the `py3rijndael` dependency

These are the updated dependencies:
- `aiohttp>=3.8.1`
- `cryptography>=35.0.0`
- `websockets>=10.2`

**Comment by epenet** [comment]
I have created three more PRs to finalise the support: #79 / #80 / #81
It would be great if you could publish a release once they are merged.

**Comment by xchwarze** [comment]
done!

**Comment by epenet** [comment]
Thanks: corresponding PR https://github.com/home-assistant/core/pull/68225
