### ISSUE TITLE
unauthorized ... how to pair with tv

### ISSUE THREAD

**Issue by jaromrax** [xchwarze/samsung-tv-ws-api#98]
Hi, 
  I tried several ways, but I end up with unauthorized access. I managed to pair the tv with `smartthings` on a phone, but I see no way to pair with python...
 Any help? Thanks
Ja

**Comment by chemelli74** [comment]
Hi,

model ?

Simone

**Comment by jaromrax** [comment]
Samsung UE32T4302
https://www.alza.cz/32-samsung-ue32t4302a-d5791100.htm

--
ip | "10.0.0.34"
model | "20_KANTS2_FHD_BASIC1"
modelName | "UE32T4302AKXXH"
name | "[TV] Samsung TV 8090"

**Comment by jaromrax** [comment]
I can start it remotely from android app SmartThings, so there is some way, in principle, to communicate with it. Thanks

**Comment by jaromrax** [comment]
This is the end of file when I run the modified example.py
```
  File "/home/pi/.local/lib/python3.7/site-packages/samsungtvws/connection.py", line 181, in open
    raise exceptions.ConnectionFailure(response)
samsungtvws.exceptions.ConnectionFailure: {'event': 'ms.channel.unauthorized'}
```

**Comment by xchwarze** [comment]
1. this doesn't use the ST (smartthings) apis, it uses the WS (websocket) locally
1. The "unauthorized" error is only triggered when the connection is not accepted on the TV. that's why it's unauthorized
