### ISSUE TITLE
app_list never returns in both sync and async version of library

### ISSUE THREAD

**Issue by kylehendricks** [xchwarze/samsung-tv-ws-api#99]
I noticed that the home assistant integration always just had "TV" and "HDMI" in my `source_list` so I decided to see if I can reproduce with the library.  I tried both the sync sample in the README and the async example from [this ticket](https://github.com/xchwarze/samsung-tv-ws-api/issues/30).  Both versions hang (seemingly) forever.

My TV is a Samsung Q90T

**Comment by xchwarze** [comment]
https://github.com/xchwarze/samsung-tv-ws-api/issues/23#issuecomment-892399358

**Comment by epenet** [comment]
We should add a comment in the code

**Comment by xchwarze** [comment]
i guess there must be an alternative in tizen 5
but no one found it yet

**Comment by xchwarze** [comment]
@epenet 
I think the change in Tizen 5 was that "installedApp" became "edenApp".
I couldn't test it yet but I think that would fix it in Tizen 5

**Comment by kylehendricks** [comment]
Tried `ed.edenApp.get` and got the same behavior.

Am I chasing the wrong thing here?  My end goal is to be able to change my TV to a specific input.  Do the "sources" show up under the apps?

**Comment by xchwarze** [comment]
**Am I chasing the wrong thing here?**
Samsung delete or rename commands. I guess as part of trying to force people to migrate to SmartThings 

**Do the "sources" show up under the apps?**
In the HA component they would have to add one of these features: 
1. Being able to manually add the array of apps 
2. Expose the method of opening app in the same way as they do with the one of changing the channel https://www.home-assistant.io/integrations/samsungtv#usage

This is the list of apps
https://github.com/balmli/com.samsung.smart/blob/master/lib/apps.js
